<?php

namespace Tests\Feature;

use App\Image;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\IntegrationTestCase;

class ImageViewTest extends IntegrationTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Storage::fake('testfs');
    }

    /** @test */
    public function a_user_can_view_image()
    {
        $this->signInDefault();

        UploadedFile::fake()->image('image.png', 300, 300)->storeAs('images/','image.png');
        create(Image::class, ['file' => 'image.png', 'path' => 'images/']);

        $response = $this->get(route('image.show', ['image' => 'image.png']))
            ->assertStatus(200);

        $response->assertHeader('Content-Type', 'image/png');
    }

    /** @test */
    public function an_unauthenticated_user_cannot_view_image()
    {
        UploadedFile::fake()->image('image.png', 300, 300)->storeAs('images/','image.png');
        create(Image::class, ['file' => 'image.png', 'path' => 'images/']);

        $this->get(route('image.show', ['image' => 'image.png']))
            ->assertRedirect(route('login'));
    }
}