<?php

namespace Tests\Feature\image;

use App\Image;
use Illuminate\Http\UploadedFile;
use Tests\IntegrationTestCase;
use Illuminate\Support\Facades\Storage;

class ImageDeleteTest extends IntegrationTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Storage::fake('testfs');
    }

    /** @test */
    public function a_user_can_delete_an_image()
    {
        $this->signInDefault();

        UploadedFile::fake()->image('image.png', 300, 300)->storeAs('images/','image.png');
        create(Image::class, ['file' => 'image.png', 'path' => 'images/']);

        Storage::disk('testfs')->assertExists('images/image.png');

        $this->delete(route('image.destroy', ['image' => 'image.png']))
            ->assertStatus(302);

        Storage::disk('testfs')->assertMissing('images/image.png');
    }

    /** @test */
    public function an_unauthenticated_user_cannot_delete_an_image()
    {
        UploadedFile::fake()->image('image.png', 300, 300)->storeAs('images/','image.png');
        create(Image::class, ['file' => 'image.png', 'path' => 'images/']);

        Storage::disk('testfs')->assertExists('images/image.png');

        $this->delete(route('image.destroy', ['image' => 'image.png']))
            ->assertRedirect(route('login'));
    }
}
